name: MMORPGCore
version: '1.0'
main: org.nakii.mmorpg.MMORPGCore
api-version: '1.21'
author: Nakii
description: A comprehensive MMORPG plugin.

softdepend: [Multiverse-Core, DecentHolograms, Vault, EffectLib, WorldEdit, WorldGuard, FancyNpcs, ZNPCsPlus, HolographicDisplays, FastAsyncWorldEdit]
depend: [ProtocolLib, Citizens]

commands:
  mmorpg:
    description: Base command for MMORPGCore admin functions (reload, zones).
    usage: /mmorpg <reload|zone|wand>
    permission: mmorpg.admin
  stats:
    description: Displays your character stats GUI.
    usage: /stats
    permission: mmorpg.command.stats
  skills:
    description: Opens the skills GUI.
    usage: /skills
    permission: mmorpg.command.skills
  giveitem:
    description: Gives a custom item.
    usage: /giveitem <item_id> [amount] [player]
    permission: mmorpg.command.giveitem
  spawnmob:
    description: Spawns a custom mob at your location.
    usage: /spawnmob <mob_id>
    permission: mmorpg.command.spawnmob
  customenchant:
    description: Applies a custom enchantment to an item or book.
    usage: /<command> <player> <enchant> <level> [item]
    permission: mmorpg.command.enchant
  slayer:
    description: Opens the Slayer quest menu.
    permission: mmorpg.command.slayer
  craft:
    description: Opens the custom crafting menu.
    aliases: [ crafting, workbench, craftingtable ]
  eco:
    description: Manages player economy.
  bank:
    description: Opens your bank account.
  debugclimate: # ADD THIS SECTION
    description: Toggles the climate debug action bar for the player.
    usage: /debugclimate
  zone:
    description: Main command for managing zones.
    usage: /zone <subcommand>
  collections:
    description: Opens collections GUI
    usage: /collections
  worldadmin:
    description: Main command for managing world settings.
    usage: /worldadmin <subcommand>
    aliases: [wa, wadmin]
  mmorpgdebug:
    description: Toggles debug mode for MMORPGCore.
    usage: /mmorpgdebug
    aliases: [mdebug]
  travel:
    description: Use to travel between worlds and zones.
    usage: /travel
  questAdmin:
    description: Admin command for managing quests.
    usage: /questAdmin <subcommand>
    aliases: [qadmin, qa]

  # BQ integration commands
  journal:
    description: Adds journal to your inventory
    usage: /<command>
    permission: betonquest.journal
    aliases: [ j, bj, bjournal, betonjournal, betonquestjournal ]
  backpack:
    description: Opens quest backpack
    usage: /<command>
    permission: betonquest.backpack
    aliases: [ b, bb, bbackpack, betonbackpack, betonquestbackpack ]
  compass:
    description: Opens the compass menu
    usage: /<command>
    permission: betonquest.compass
    aliases: [ bc, bcompass, betoncompass, betonquestcompass ]
  cancelquest:
    description: Opens the window with quest cancelers
    usage: /<command>
    permission: betonquest.cancelquest
    aliases: [ bcq, bcancelquest, betoncancelquest, betonquestcancelquest ]
  questlang:
    description: Changes the language
    usage: /<command> lang
    permission: betonquest.language
    aliases: [ ql ]
  betonquest:
    description: General quest command
    usage: /<command>
    permission: betonquest.admin
    aliases: [ q, bq, bquest, bquests, betonquests, quest, quests ]
  betonquestanswer:
    description: Selects an answer in a conversation
    usage: No manual usage

permissions:
  mmorpg.admin:
    description: Grants access to all MMORPGCore administrative commands.
    default: op
  mmorpg.command.giveitem:
    description: Allows the user to use the /giveitem command.
    default: op
  mmorpg.command.spawnmob:
    description: Allows the user to use the /spawnmob command.
    default: op
  mmorpg.command.stats:
    description: Allows the user to use the /stats command.
    default: true
  mmorpg.command.skills:
    description: Allows the user to use the /skills command.
    default: true
  mmorpg.command.enchant:
    description: Allow the user to use the /customenchant command.
    default: true
  mmorpg.command.openhex:
    description: Allow the user to use the /openhex command.
    default: true
  mmorpg.command.slayer:
    description: Allow the user to use the /slayer command.
    default: true
  betonquest.admin:
    default: op
  betonquest.journal:
    default: true
  betonquest.backpack:
    default: true
  betonquest.cancelquest:
    default: true
  betonquest.compass:
    default: true
  betonquest.conversation:
    default: true
  betonquest.language:
    default: true
