name: MMORPGCore
version: '1.0'
main: org.nakii.mmorpg.MMORPGCore
api-version: '1.21'
author: Nakii
description: A comprehensive MMORPG plugin.

softdepend: [LibsDisguises]

commands:
  mmorpg:
    description: Base command for MMORPGCore admin functions (reload, zones).
    usage: /mmorpg <reload|zone|wand>
    permission: mmorpg.admin
  stats:
    description: Displays your character stats GUI.
    usage: /stats
    permission: mmorpg.command.stats
  skills:
    description: Opens the skills GUI.
    usage: /skills
    permission: mmorpg.command.skills

  # --- NEW COMMANDS ---
  giveitem:
    description: Gives a custom item.
    usage: /giveitem <item_id> [amount] [player]
    permission: mmorpg.command.giveitem
  spawnmob:
    description: Spawns a custom mob at your location.
    usage: /spawnmob <mob_id>
    permission: mmorpg.command.spawnmob
  customenchant:
    description: Applies a custom enchantment to an item or book.
    usage: /<command> <player> <enchant> <level> [item]
    permission: mmorpg.command.enchant
  openhex:
    description: Opens The Hex GUI for enchantment removal.
    usage: /<command>
    permission: mmorpg.command.openhex
  slayer:
    description: Opens the Slayer quest menu.
    permission: mmorpg.command.slayer

permissions:
  mmorpg.admin:
    description: Grants access to all MMORPGCore administrative commands.
    default: op

  # --- NEW PERMISSIONS ---
  mmorpg.command.giveitem:
    description: Allows the user to use the /giveitem command.
    default: op
  mmorpg.command.spawnmob:
    description: Allows the user to use the /spawnmob command.
    default: op

  # Base user permissions
  mmorpg.command.stats:
    description: Allows the user to use the /stats command.
    default: true
  mmorpg.command.skills:
    description: Allows the user to use the /skills command.
    default: true
  mmorpg.command.enchant:
    description: Allow the user to use the /customenchant command.
    default: true
  mmorpg.command.openhex:
    description: Allow the user to use the /openhex command.
    default: true
  mmorpg.command.slayer:
    description: Allow the user to use the /slayer command.
    default: true
